# 游깷 GMC Ecosystem - Environment Configurations
# Configura칞칫es centralizadas para todos os ambientes

version: "1.0"
last_updated: "2024-12-19"

# =============================================================================
# CONFIGURA칂칏ES GLOBAIS
# =============================================================================
global:
  project_name: "GMC Ecosystem"
  version: "1.0.0"
  rust_version: "1.75.0"
  anchor_version: "0.30.1"
  solana_version: "1.18.24"
  node_version: "18.x"
  
  # Timeouts globais
  timeouts:
    connection: 30000      # 30s
    transaction: 60000     # 60s
    deployment: 1800000    # 30min
    
  # Limites de retry
  retry_limits:
    max_attempts: 5
    backoff_multiplier: 2
    initial_delay: 1000

# =============================================================================
# DEVNET - DESENVOLVIMENTO
# =============================================================================
devnet:
  metadata:
    name: "Development Network"
    description: "Ambiente para desenvolvimento e testes r치pidos"
    purpose: "Itera칞칚o r치pida e prototipagem"
    
  network:
    cluster: "devnet"
    rpc_urls:
      primary: "https://api.devnet.solana.com"
      fallback:
        - "https://solana-devnet.g.alchemy.com/v2/demo"
        - "https://devnet.helius-rpc.com/?api-key=demo"
    commitment: "confirmed"
    
  security:
    level: "basic"
    require_multisig: false
    max_transaction_size: 1000000
    deployment_timeout: 300000  # 5 min
    verification_required: false
    audit_required: false
    
  sol_management:
    target_balance: 25.0
    minimum_balance: 5.0
    airdrop_amount: 2.0
    max_airdrop_attempts: 50
    collection_strategies:
      - "cli_airdrop"
      - "faucet_rotation"
      - "buffer_recovery"
      - "auxiliary_wallets"
    
  wallets:
    deployer: "./keypairs/devnet/deployer.json"
    admin: "./keypairs/devnet/admin.json"
    team: "./keypairs/devnet/team.json"
    treasury: "./keypairs/devnet/treasury.json"
    marketing: "./keypairs/devnet/marketing.json"
    airdrop: "./keypairs/devnet/airdrop.json"
    
  programs:
    gmc_token: "TBD"  # Ser치 definido ap칩s deploy
    gmc_staking: "TBD"
    gmc_ranking: "TBD"
    gmc_vesting: "TBD"
    gmc_treasury: "TBD"
    
  tokenomics:
    total_supply: 100000000
    distribution:
      staking_pool: 70000000
      pre_ico: 8000000
      reserve: 10000000
      treasury: 2000000
      marketing: 6000000
      airdrop: 2000000
      team: 2000000
      
  fees:
    transfer_fee_basis_points: 50  # 0.5%
    staking_entry_fees: [10, 5, 2.5, 1, 0.5]  # Por tier
    burn_for_boost_fee: 0.8  # USDT
    
  monitoring:
    enabled: true
    log_level: "debug"
    metrics_retention: "7d"
    alerts:
      slack: false
      email: false
      
  deployment:
    auto_deploy: true
    rollback_enabled: true
    backup_required: false
    approval_required: false

# =============================================================================
# TESTNET - HOMOLOGA칂츾O
# =============================================================================
testnet:
  metadata:
    name: "Test Network"
    description: "Ambiente para valida칞칚o e bug bounty"
    purpose: "Valida칞칚o completa antes da produ칞칚o"
    
  network:
    cluster: "testnet"
    rpc_urls:
      primary: "https://api.testnet.solana.com"
      fallback:
        - "https://solana-testnet.g.alchemy.com/v2/demo"
    commitment: "finalized"
    
  security:
    level: "high"
    require_multisig: true
    max_transaction_size: 1000000
    deployment_timeout: 600000  # 10 min
    verification_required: true
    audit_required: true
    
  sol_management:
    target_balance: 50.0
    minimum_balance: 10.0
    manual_funding: true  # Sem airdrop autom치tico
    
  wallets:
    deployer: "./keypairs/testnet/deployer.json"
    admin: "./keypairs/testnet/admin.json"
    team: "./keypairs/testnet/team.json"
    treasury: "./keypairs/testnet/treasury.json"
    marketing: "./keypairs/testnet/marketing.json"
    airdrop: "./keypairs/testnet/airdrop.json"
    
  programs:
    gmc_token: "TBD"
    gmc_staking: "TBD"
    gmc_ranking: "TBD"
    gmc_vesting: "TBD"
    gmc_treasury: "TBD"
    
  tokenomics:
    total_supply: 100000000
    distribution:
      staking_pool: 70000000
      pre_ico: 8000000
      reserve: 10000000
      treasury: 2000000
      marketing: 6000000
      airdrop: 2000000
      team: 2000000
      
  fees:
    transfer_fee_basis_points: 50
    staking_entry_fees: [10, 5, 2.5, 1, 0.5]
    burn_for_boost_fee: 0.8
    
  monitoring:
    enabled: true
    log_level: "info"
    metrics_retention: "30d"
    alerts:
      slack: true
      email: true
      
  deployment:
    auto_deploy: false
    rollback_enabled: true
    backup_required: true
    approval_required: true
    
  bug_bounty:
    enabled: true
    total_pool: 50000  # USDT
    rewards:
      critical: 10000
      high: 5000
      medium: 2000
      low: 500
      info: 100

# =============================================================================
# MAINNET - PRODU칂츾O
# =============================================================================
mainnet:
  metadata:
    name: "Main Network"
    description: "Ambiente de produ칞칚o com fundos reais"
    purpose: "Opera칞칚o comercial do GMC Ecosystem"
    
  network:
    cluster: "mainnet-beta"
    rpc_urls:
      primary: "https://api.mainnet-beta.solana.com"
      fallback:
        - "https://solana-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
        - "https://rpc.ankr.com/solana"
    commitment: "finalized"
    
  security:
    level: "maximum"
    require_multisig: true
    max_transaction_size: 500000
    deployment_timeout: 900000  # 15 min
    verification_required: true
    audit_required: true
    
  sol_management:
    target_balance: 100.0
    minimum_balance: 20.0
    manual_funding: true
    emergency_reserve: 50.0
    
  wallets:
    deployer: "./keypairs/mainnet/deployer.json"
    admin: "./keypairs/mainnet/admin.json"
    team: "./keypairs/mainnet/team.json"
    treasury: "./keypairs/mainnet/treasury.json"
    marketing: "./keypairs/mainnet/marketing.json"
    airdrop: "./keypairs/mainnet/airdrop.json"
    
  programs:
    gmc_token: "TBD"
    gmc_staking: "TBD"
    gmc_ranking: "TBD"
    gmc_vesting: "TBD"
    gmc_treasury: "TBD"
    
  tokenomics:
    total_supply: 100000000
    distribution:
      staking_pool: 70000000
      pre_ico: 8000000
      reserve: 10000000
      treasury: 2000000
      marketing: 6000000
      airdrop: 2000000
      team: 2000000
      
  fees:
    transfer_fee_basis_points: 50
    staking_entry_fees: [10, 5, 2.5, 1, 0.5]
    burn_for_boost_fee: 0.8
    
  monitoring:
    enabled: true
    log_level: "warn"
    metrics_retention: "1y"
    alerts:
      slack: true
      email: true
      sms: true
      pagerduty: true
      
  deployment:
    auto_deploy: false
    rollback_enabled: true
    backup_required: true
    approval_required: true
    ceremony_required: true
    
  emergency:
    contacts:
      - "lead-dev@gmc-ecosystem.com"
      - "security@gmc-ecosystem.com"
      - "devops@gmc-ecosystem.com"
    procedures:
      - "pause_all_contracts"
      - "notify_emergency_team"
      - "assess_damage"
      - "execute_recovery_plan"
    recovery_time_objective: 3600  # 1 hour
    
  compliance:
    soc2: true
    iso27001: true
    audit_frequency: "quarterly"
    penetration_testing: "monthly"
    
# =============================================================================
# CONFIGURA칂칏ES DE INTEGRA칂츾O
# =============================================================================
integrations:
  github:
    repository: "gmc-ecosystem/gmc-token"
    branch_protection: true
    required_reviews: 2
    
  slack:
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      alerts: "#gmc-alerts"
      deployments: "#gmc-deployments"
      security: "#gmc-security"
      
  monitoring:
    prometheus:
      enabled: true
      port: 9090
    grafana:
      enabled: true
      port: 3000
    elk_stack:
      enabled: true
      elasticsearch_port: 9200
      
  vault:
    enabled: true
    url: "${VAULT_URL}"
    auth_method: "kubernetes"
    
# =============================================================================
# TEMPLATES DE CONFIGURA칂츾O
# =============================================================================
templates:
  keypair_generation:
    algorithm: "ed25519"
    entropy_source: "/dev/urandom"
    backup_required: true
    
  program_deployment:
    verify_build: true
    test_before_deploy: true
    backup_before_upgrade: true
    
  monitoring_setup:
    metrics_collection: true
    log_aggregation: true
    alert_rules: true
    dashboard_creation: true