# 🔒 GMC Ecosystem - Security Policies
# Políticas de segurança baseadas em OWASP Top 10 Smart Contracts e melhores práticas

version: "1.0"
last_updated: "2024-12-19"
compliance_frameworks:
  - "OWASP Top 10 Smart Contracts"
  - "NIST Cybersecurity Framework"
  - "ISO 27001"
  - "SOC 2 Type II"
  - "Solana Security Best Practices"

# =============================================================================
# POLÍTICAS GERAIS DE SEGURANÇA
# =============================================================================
general_policies:
  security_by_design:
    enabled: true
    description: "Segurança integrada desde o design"
    requirements:
      - "Threat modeling obrigatório para novos recursos"
      - "Security review em todas as mudanças"
      - "Princípio do menor privilégio"
      - "Defense in depth"
      
  zero_trust:
    enabled: true
    description: "Arquitetura Zero Trust"
    principles:
      - "Never trust, always verify"
      - "Verify explicitly"
      - "Use least privilege access"
      - "Assume breach"
      
  shift_left:
    enabled: true
    description: "Segurança no início do SDLC"
    practices:
      - "Security testing em CI/CD"
      - "Static analysis automático"
      - "Dependency scanning"
      - "Secret scanning"

# =============================================================================
# OWASP TOP 10 SMART CONTRACTS - CONTROLES
# =============================================================================
owasp_smart_contracts:
  SC01_reentrancy:
    severity: "critical"
    description: "Proteção contra ataques de reentrância"
    controls:
      - name: "ReentrancyGuard"
        type: "preventive"
        implementation: "Anchor framework automático"
        testing: "Unit tests específicos"
      - name: "Checks-Effects-Interactions"
        type: "preventive"
        implementation: "Pattern obrigatório"
        testing: "Code review"
    monitoring:
      - "Transaction pattern analysis"
      - "Unusual call stack detection"
      
  SC02_integer_overflow:
    severity: "high"
    description: "Proteção contra overflow/underflow"
    controls:
      - name: "Safe Math"
        type: "preventive"
        implementation: "checked_add, checked_sub, checked_mul"
        testing: "Boundary value testing"
      - name: "Input Validation"
        type: "preventive"
        implementation: "Range checks obrigatórios"
        testing: "Fuzzing"
    monitoring:
      - "Arithmetic operation monitoring"
      - "Large number transaction alerts"
      
  SC03_timestamp_dependence:
    severity: "medium"
    description: "Uso seguro de timestamps"
    controls:
      - name: "Clock Validation"
        type: "preventive"
        implementation: "Clock::get() validation"
        testing: "Time manipulation tests"
      - name: "Tolerance Windows"
        type: "preventive"
        implementation: "Acceptable time ranges"
        testing: "Edge case testing"
    monitoring:
      - "Timestamp anomaly detection"
      - "Clock drift monitoring"
      
  SC04_authorization:
    severity: "critical"
    description: "Controle de acesso adequado"
    controls:
      - name: "Signer Validation"
        type: "preventive"
        implementation: "Anchor signer checks"
        testing: "Authorization tests"
      - name: "Role-Based Access"
        type: "preventive"
        implementation: "RBAC implementation"
        testing: "Privilege escalation tests"
    monitoring:
      - "Unauthorized access attempts"
      - "Privilege usage monitoring"
      
  SC05_unprotected_withdrawal:
    severity: "critical"
    description: "Proteção de retiradas de tokens"
    controls:
      - name: "Balance Validation"
        type: "preventive"
        implementation: "Pre-transfer checks"
        testing: "Insufficient balance tests"
      - name: "Withdrawal Limits"
        type: "preventive"
        implementation: "Rate limiting"
        testing: "Limit bypass tests"
    monitoring:
      - "Large withdrawal alerts"
      - "Unusual withdrawal patterns"
      
  SC06_selfdestruct:
    severity: "high"
    description: "Proteção contra destruição não autorizada"
    controls:
      - name: "Close Protection"
        type: "preventive"
        implementation: "Admin-only close"
        testing: "Unauthorized close tests"
    monitoring:
      - "Account close monitoring"
      
  SC07_floating_pragma:
    severity: "low"
    description: "Versões fixas de dependências"
    controls:
      - name: "Version Pinning"
        type: "preventive"
        implementation: "Cargo.toml version locks"
        testing: "Dependency audit"
    monitoring:
      - "Dependency update alerts"
      
  SC08_function_visibility:
    severity: "medium"
    description: "Visibilidade adequada de funções"
    controls:
      - name: "Explicit Visibility"
        type: "preventive"
        implementation: "pub/private explicit"
        testing: "Access control tests"
    monitoring:
      - "Function call monitoring"
      
  SC09_gas_limit:
    severity: "medium"
    description: "Proteção contra DoS por gas"
    controls:
      - name: "Loop Limits"
        type: "preventive"
        implementation: "Bounded iterations"
        testing: "Gas consumption tests"
    monitoring:
      - "High gas usage alerts"
      
  SC10_unhandled_exception:
    severity: "medium"
    description: "Tratamento adequado de erros"
    controls:
      - name: "Error Handling"
        type: "preventive"
        implementation: "Custom error types"
        testing: "Error condition tests"
    monitoring:
      - "Error rate monitoring"

# =============================================================================
# POLÍTICAS POR AMBIENTE
# =============================================================================
environment_policies:
  devnet:
    security_level: "basic"
    required_controls:
      - "Basic input validation"
      - "Error handling"
      - "Logging"
    optional_controls:
      - "Advanced monitoring"
    testing_requirements:
      - "Unit tests"
      - "Basic integration tests"
      
  testnet:
    security_level: "high"
    required_controls:
      - "All OWASP Top 10 controls"
      - "Comprehensive logging"
      - "Real-time monitoring"
      - "Automated alerting"
    testing_requirements:
      - "Full test suite"
      - "Security testing"
      - "Penetration testing"
      - "Bug bounty validation"
      
  mainnet:
    security_level: "maximum"
    required_controls:
      - "All security controls"
      - "Multi-signature requirements"
      - "Emergency procedures"
      - "Incident response"
    testing_requirements:
      - "Complete test coverage"
      - "External security audit"
      - "Formal verification"
      - "Continuous monitoring"

# =============================================================================
# CONTROLES DE ACESSO
# =============================================================================
access_controls:
  authentication:
    methods:
      - "Cryptographic signatures"
      - "Multi-factor authentication"
      - "Hardware security modules"
    requirements:
      - "Strong key generation"
      - "Secure key storage"
      - "Key rotation policies"
      
  authorization:
    model: "RBAC"  # Role-Based Access Control
    roles:
      admin:
        permissions:
          - "deploy_contracts"
          - "upgrade_programs"
          - "emergency_pause"
          - "fund_management"
        environments: ["devnet", "testnet", "mainnet"]
        
      developer:
        permissions:
          - "deploy_contracts"
          - "run_tests"
          - "view_logs"
        environments: ["devnet", "testnet"]
        
      auditor:
        permissions:
          - "view_logs"
          - "run_security_scans"
          - "generate_reports"
        environments: ["devnet", "testnet", "mainnet"]
        
      operator:
        permissions:
          - "view_monitoring"
          - "acknowledge_alerts"
        environments: ["mainnet"]

# =============================================================================
# GESTÃO DE SECRETS
# =============================================================================
secrets_management:
  storage:
    method: "HashiCorp Vault"
    encryption: "AES-256-GCM"
    backup: "Encrypted offsite"
    
  rotation:
    frequency:
      keypairs: "quarterly"
      api_keys: "monthly"
      passwords: "monthly"
    automation: true
    
  access:
    principle: "least_privilege"
    logging: "all_access_logged"
    approval: "required_for_production"
    
  policies:
    - "No secrets in code"
    - "No secrets in logs"
    - "Encrypted transmission"
    - "Secure deletion"

# =============================================================================
# MONITORAMENTO E DETECÇÃO
# =============================================================================
monitoring_policies:
  logging:
    level:
      devnet: "debug"
      testnet: "info"
      mainnet: "warn"
    retention:
      devnet: "7 days"
      testnet: "30 days"
      mainnet: "1 year"
    format: "structured_json"
    
  metrics:
    collection_interval: "30s"
    retention:
      short_term: "7 days"
      long_term: "1 year"
    alerting:
      response_time: "< 5 minutes"
      escalation: "automatic"
      
  security_events:
    detection:
      - "Failed authentication attempts"
      - "Unusual transaction patterns"
      - "Large fund movements"
      - "System anomalies"
    response:
      - "Automatic alerting"
      - "Incident creation"
      - "Escalation procedures"
      
  compliance:
    audit_trail: "immutable"
    data_integrity: "cryptographic_hashes"
    access_logs: "comprehensive"

# =============================================================================
# RESPOSTA A INCIDENTES
# =============================================================================
incident_response:
  classification:
    P0_critical:
      description: "Perda de fundos ou sistema comprometido"
      response_time: "< 15 minutes"
      escalation: "immediate"
      
    P1_high:
      description: "Funcionalidade crítica afetada"
      response_time: "< 1 hour"
      escalation: "within_2_hours"
      
    P2_medium:
      description: "Degradação de performance"
      response_time: "< 4 hours"
      escalation: "within_8_hours"
      
    P3_low:
      description: "Problemas menores"
      response_time: "< 24 hours"
      escalation: "within_48_hours"
      
  procedures:
    detection:
      - "Automated monitoring"
      - "User reports"
      - "Security scans"
      
    containment:
      - "Isolate affected systems"
      - "Preserve evidence"
      - "Prevent spread"
      
    investigation:
      - "Root cause analysis"
      - "Impact assessment"
      - "Timeline reconstruction"
      
    recovery:
      - "System restoration"
      - "Data recovery"
      - "Service resumption"
      
    lessons_learned:
      - "Post-mortem analysis"
      - "Process improvements"
      - "Control updates"

# =============================================================================
# COMPLIANCE E AUDITORIA
# =============================================================================
compliance:
  frameworks:
    soc2:
      enabled: true
      audit_frequency: "annual"
      controls_mapping: "automated"
      
    iso27001:
      enabled: true
      certification_target: "Q2_2025"
      gap_analysis: "quarterly"
      
  auditing:
    internal:
      frequency: "monthly"
      scope: "all_environments"
      automation: "maximum"
      
    external:
      frequency: "quarterly"
      scope: "production_systems"
      vendors: ["Trail of Bits", "ConsenSys Diligence"]
      
  reporting:
    frequency: "monthly"
    stakeholders:
      - "CISO"
      - "CTO"
      - "Compliance Officer"
      - "Board of Directors"
    metrics:
      - "Security posture score"
      - "Vulnerability trends"
      - "Incident statistics"
      - "Compliance status"

# =============================================================================
# TREINAMENTO E CONSCIENTIZAÇÃO
# =============================================================================
training:
  security_awareness:
    frequency: "quarterly"
    mandatory: true
    topics:
      - "Phishing awareness"
      - "Social engineering"
      - "Secure coding practices"
      - "Incident reporting"
      
  specialized_training:
    smart_contract_security:
      audience: "developers"
      frequency: "bi-annual"
      certification: "required"
      
    incident_response:
      audience: "security_team"
      frequency: "quarterly"
      simulation: "required"
      
  continuous_learning:
    security_champions: true
    knowledge_sharing: "monthly"
    threat_intelligence: "weekly"
    
# =============================================================================
# MÉTRICAS E KPIS
# =============================================================================
metrics:
  security_kpis:
    - name: "Mean Time to Detection (MTTD)"
      target: "< 15 minutes"
      measurement: "automated"
      
    - name: "Mean Time to Response (MTTR)"
      target: "< 1 hour"
      measurement: "incident_tracking"
      
    - name: "Vulnerability Remediation Time"
      target: "< 7 days (critical), < 30 days (high)"
      measurement: "vulnerability_scanner"
      
    - name: "Security Test Coverage"
      target: "> 95%"
      measurement: "automated_testing"
      
    - name: "Compliance Score"
      target: "> 98%"
      measurement: "compliance_dashboard"
      
  operational_kpis:
    - name: "System Availability"
      target: "99.9%"
      measurement: "uptime_monitoring"
      
    - name: "Deploy Success Rate"
      target: "99%"
      measurement: "ci_cd_pipeline"
      
    - name: "Security Incident Rate"
      target: "< 1 per month"
      measurement: "incident_tracking"

# =============================================================================
# POLÍTICAS DE EXCEÇÃO
# =============================================================================
exceptions:
  process:
    approval_required: true
    approvers:
      - "CISO"
      - "CTO"
    documentation: "mandatory"
    review_frequency: "monthly"
    
  criteria:
    business_justification: "required"
    risk_assessment: "mandatory"
    compensating_controls: "required"
    time_limit: "maximum_90_days"
    
  monitoring:
    exception_tracking: "automated"
    compliance_impact: "assessed"
    remediation_plan: "required"