[package]
name = "gmc_token_native"
version = "1.0.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# Versões específicas para máxima compatibilidade SBPF v1
solana-program = "=1.17.31"
borsh = "=0.9.3"

[dev-dependencies]
solana-program-test = "=1.17.31"
